### ISSUE TITLE
(Enhancement) Add the ITUNESADVISORY tag to tracks if they have Explicit label.

### ISSUE THREAD

**Issue by ShadyRelapse-PP** [yarrm80s/orpheusdl-qobuz#5]
Would it be possible to add iTunes Explicit tags to be added to the tracks if they have Explicit labels on qobuz?

**Comment by yarrm80s** [comment]
@ShadyRelapse-PP Yes, add "{explicit}" to your path. Note that it includes the space before [E] when needed so don't add the space yourself

**Comment by yarrm80s** [comment]
Oh wait what? I just re-read your question... the tags are already added...?

**Comment by Dniel97** [comment]
`ITUNESADVISORY` is only working for MPEG-4 container formats and already implemented here: [tagging.py#50](https://github.com/yarrm80s/orpheusdl/blob/ab2a3eed156e31152f510d5b4ed9f67dbfac5392/orpheus/tagging.py#L50). There is no need for the `ITUNESADVISORY` tag in FLAC files, because it looks ugly instead FLAC files are using an dedicated `Rating` VORBIS comment tag with the values `Explicit` or `Clean` as seen here: [tagging.py#111](https://github.com/yarrm80s/orpheusdl/blob/ab2a3eed156e31152f510d5b4ed9f67dbfac5392/orpheus/tagging.py#L111). Hope this answers the question, there is no plan to include the `ITUNESADVISORY` tag for FLAC files.
