### ISSUE TITLE
I'm probably doing something wrong. SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by z0rg0n** [yarrm80s/orpheusdl-qobuz#7]
I followed the getting started steps in these pages:
https://github.com/yarrm80s/orpheusdl#installation
https://github.com/yarrm80s/orpheusdl-qobuz

The settings.json file has been updated with my account email and password along with the app credentials I got here:
http://shell.cyberia.is/~albino/qobuz-creds.html

When I run `python orpheus.py https://open.qobuz.com/album/0007502101475`
I get the error:
```
File "orpheus.py", line 70
    raise Exception(f'Unknown setting "{modulesetting}" for module "{setting}"')
                                                                              ^
SyntaxError: invalid syntax
```

I assume this has to do with my settings.json file but I'm not sure what I'm screwing up.

**Comment by yarrm80s** [comment]
@z0rg0n Your python version must be extremely old, since that is an error from well before python even starts executing any of the code. Also, the app ID and secret pair might not work, since it seems like that website you're using is taking the keys from the website, while I wrote the module with the Android version's keys in mind (if you want more details on that, join the Telegram https://t.me/orpheusdl)

**Comment by z0rg0n** [comment]
100% that was it.

I was so used to only python3 being installed that I didn't realize my vm had an old version was defaulting to 2.

Looks like the keys you mentioned are the only issue now. Thanks for the info!
